# Generated by Django 5.0.4 on 2024-05-01 20:58

import aviasales.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interface_language', models.CharField(max_length=25)),
                ('city_of_residence', models.CharField(max_length=40)),
                ('currency', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departure_location', models.CharField(max_length=50)),
                ('arrival_location', models.CharField(max_length=50)),
                ('flight', models.CharField(max_length=50)),
                ('airplane', models.CharField(max_length=50)),
                ('sent_in_plane', models.CharField(max_length=50)),
                ('number_of_passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=16, validators=[aviasales.models.validate_phone_number])),
                ('email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related', to='aviasales.settings')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='aviasales.user'),
        ),
        migrations.CreateModel(
            name='PurchasedTickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time_of_creation', models.DateTimeField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_state', models.CharField(max_length=50)),
                ('payment_time', models.DateTimeField()),
                ('status', models.CharField(max_length=15)),
                ('tickets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviasales.tickets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviasales.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tickets', models.ManyToManyField(to='aviasales.tickets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aviasales.user')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citizenship', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aviasales.user')),
            ],
        ),
    ]
